# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-19 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='lasttname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=25),
        ),
    ]
