# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-25 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20190219_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='phone_number',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
