# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-25 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_register_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='first_name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='last_name',
        ),
        migrations.AddField(
            model_name='register',
            name='catergory',
            field=models.CharField(default='thuongpham90', max_length=25),
            preserve_default=False,
        ),
    ]
