# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-27 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_auto_20190227_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
